version: "3"

services:
  uptimerobot-page:
    image: nangle/status-page
    # build: .
    environment: 
      - PORT=3000
      - LOG_LEVEL=info
      - CRON_TIME=*/1 * * * *
      - UPTIME_ROBOT_API=
      - UPTIME_ROBOT_NAME_PATTERN=%group/%name
      - WEBSITE_TITLE=
      - WEBSITE_COPYRIGHT=
    # To use config file for more flexible configure,
    # please uncomment next block
    volumes:
      - ./config:/app/config
    ports: 
      - "3000:3000"
