app:
  port: 3000
  log_level: info
  crontime: "*/1 * * * *"

uptimerobot:
  api_key: ur894242-90d1eb90acc82624bcaed27a
  pattern: "%group/%index/%name"
  statuses: "2-9"

website:
  title: "服务状态"
  copyright: "极客青年"
  links:
    - name: 主页
      href: https://home.java666.cn
    - name: GitHub
      href: http://github.com/geekyouth
